name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
         
      - name: Deploy to DEV environment
        if: github.ref_type == 'tag' && endsWith(github.ref_name, 'dev')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /apps/dev_teletapp_webapp
            pwd
            ls -la

      - name: Deploy to PROD environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /apps/teletapp_webapp
            pwd
            ls -la
