name: Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to server
        run: |
          ssh -i id_rsa root@185.43.6.202 "cd /apps/teletapp_webapp/teletapp_webapp && git pull && docker compose up -d"

      - name: Deploy to dev server
        run: |
          ssh -i id_rsa root@185.43.6.202 "cd /apps/teletapp_webapp/dev_teletapp_webapp && git pull && docker compose up -d"
